### ISSUE TITLE
Apple TV Support

### ISSUE THREAD

**Issue by netwarex** [unknownskl/xbox-xcloud-player#189]
Hi,

I wondering if Apple TV Support would be possible using https://developer.apple.com/documentation/tvmljs and your efforts together?

**Comment by unknownskl** [comment]
I dont think so. WebRTC seems to be quite limited on tvOS and it is not a goal of this project. I will keep an eye on cross-platform possibilities for in the future but right now this is not the goal of this project. Maybe later in the future with a different name.
