### ISSUE TITLE
STUCK  ON GETTING STREAM READY PROVISIONING

### ISSUE THREAD

**Issue by Micah0220** [unknownskl/xbox-xcloud-player#242]
program wont load a preview of my xbox. pulling my hair out because im stuck or the program is broken, please someone help! :(
heres a screenshot: https://ibb.co/HHqmG2Q

**Comment by unknownskl** [comment]
Download the newest version. This screenshot is from v1.2.0

**Comment by Micah0220** [comment]
> Download the newest version. This screenshot is from v1.2.0

do you have a link? i just downloaded from windows store where it was sold

**Comment by unknownskl** [comment]
> > Download the newest version. This screenshot is from v1.2.0
> 
> do you have a link? i just downloaded from windows store where it was sold

Greenlight is free. If anyone sold you this then please report them and ask your money back.

Greenlight can be downloaded for free here: https://github.com/unknownskl/greenlight
