### ISSUE TITLE
Localhost:3000 giving a error 

### ISSUE THREAD

**Issue by ilixity** [unknownskl/xbox-xcloud-player#291]
When running the build and watch it shows me this error
{"error":{"line":1,"column":43341,"sourceURL":"https://917aec57-767b-4ac8-9614-3e279bc54696-00-164b650a3z8qv.riker.replit.dev/dist/xCloudPlayer.min.js"}}
And I can’t figure out what’s wrong. Is it just me? 
![IMG_0731](https://github.com/unknownskl/xbox-xcloud-player/assets/142562717/fb24743a-6cfd-4275-95cb-168b7d6b25e4)

**Comment by unknownskl** [comment]
What does the console say when you open the network debugging tools? Also check the network tab for the response.

**Comment by ilixity** [comment]
> What does the console say when you open the network debugging tools? Also check the network tab for the response.

How do i open the network debugging tools?

**Comment by ilixity** [comment]
> Right mouse click on the white page and then select inspect element. A bar opens from the bottom or the side and from there you can click the console. If you are not familiar with web tools then this aint the right package for you, you probably want to check out [greenlight](https://github.com/unknownskl/greenlight) instead.

Okay I’m gonna go check that out. Thank you
